import { useState } from 'react'
import { PageHeader } from '../../../shared/components/PageHeader'
import type { RecommendationStatus } from '../../../shared/types/domain'
import { ActiveModeBanner } from '../../modes/components/ActiveModeBanner'
import { RecommendationsList } from '../components/RecommendationsList'
import { useRecommendations } from '../hooks/useRecommendations'

const statuses: RecommendationStatus[] = [
  'OPEN',
  'ACCEPTED',
  'POSTPONED',
  'DISMISSED',
]

export function RecommendationsPage() {
  const [status, setStatus] = useState<RecommendationStatus>('OPEN')
  const {
    recommendationsQuery,
    acceptRecommendation,
    postponeRecommendation,
    dismissRecommendation,
  } = useRecommendations({ status })

  const isActionPending =
    acceptRecommendation.isPending ||
    postponeRecommendation.isPending ||
    dismissRecommendation.isPending

  return (
    <>
      <PageHeader
        title="Recommendations"
        description="Rule-based recommendations generated by the backend from the latest score snapshot and risk factors."
      />

      <section className="mb-5">
        <ActiveModeBanner compact />
      </section>

      <div className="mb-5 flex flex-wrap gap-2">
        {statuses.map((item) => (
          <button
            key={item}
            type="button"
            onClick={() => setStatus(item)}
            className={`rounded-md border px-3 py-2 text-sm font-semibold ${
              status === item
                ? 'border-teal-700 bg-teal-700 text-white'
                : 'border-slate-300 bg-white text-slate-700 hover:bg-slate-50'
            }`}
          >
            {item}
          </button>
        ))}
      </div>

      {recommendationsQuery.isLoading ? (
        <p className="text-sm text-slate-600">Loading recommendations...</p>
      ) : (
        <RecommendationsList
          recommendations={recommendationsQuery.data ?? []}
          isActionPending={isActionPending}
          emptyTitle={`No ${status.toLowerCase()} recommendations`}
          emptyDescription="Create a scenario, add expenses, calculate score, and recalculate recommendations to populate this list."
          onAccept={(id) =>
            acceptRecommendation.mutate({
              id,
              payload: { reason: 'Accepted from recommendations page' },
            })
          }
          onPostpone={(id) =>
            postponeRecommendation.mutate({
              id,
              payload: { reason: 'Postponed from recommendations page' },
            })
          }
          onDismiss={(id) =>
            dismissRecommendation.mutate({
              id,
              payload: { reason: 'Dismissed from recommendations page' },
            })
          }
        />
      )}
    </>
  )
}
