package com.tranquiloos.decisions.domain;

public enum DecisionType {
	RECOMMENDATION_ACCEPTED,
	RECOMMENDATION_POSTPONED,
	RECOMMENDATION_DISMISSED,
	SCENARIO_COMPARED,
	SCENARIO_SELECTED,
	MODE_ACTIVATED,
	PURCHASE_BOUGHT,
	PURCHASE_POSTPONED,
	TRANSPORT_EVALUATED,
	SCORE_CALCULATED
}
